# Generated by Django 4.1.7 on 2023-03-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_about_author_blogger_about_blogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='about_blogger',
            new_name='about',
        ),
    ]
