# Generated by Django 4.1.7 on 2023-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_about_blogger_blogger_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
