# Generated by Django 4.1.7 on 2023-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogger_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>'),
        ),
    ]
