# Generated by Django 4.1.7 on 2023-04-05 14:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0013_blogpost_last_updated_alter_blogpost_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostAuthorPermission',
            fields=[
            ],
            options={
                'verbose_name': 'Can edit own blog post',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
