# Generated by Django 4.1.7 on 2023-04-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpostauthorpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostAuthorPermission',
        ),
    ]
