# Generated by Django 4.1.7 on 2023-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='default-title', max_length=200),
            preserve_default=False,
        ),
    ]
