# Generated by Django 4.1.7 on 2023-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default='user2023-04-08 14:50:08.013629+00:00'),
            preserve_default=False,
        ),
    ]
