# Generated by Django 4.1.7 on 2023-04-10 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogger_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 4, 10, 3, 22, 30, 965299, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
